---
abstract: 'PostgreSQL schema for App::ProxyHunter'
author:
  - 'Oleg G <oleg@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ProxyHunter-Model-Schema-Pg
no_index:
  directory:
    - t
    - inc
requires:
  App::ProxyHunter: 0.01
  DBD::Pg: 0.4
  DateTime::Format::Pg: 0
resources:
  repository: https://github.com/olegwtf/p5-App-ProxyHunter-Model-Schema-Pg
version: 0.01
